[phases.build]
cmds = ["npm run build"]

[phases.install]
cmds = ["npm ci"]
dependsOn = ["setup"]

[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]

[variables]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"

[mounts]
"/app/.data" = "snapense_db"

[start]
cmd = "node server.js"
